version: '2'
services:
  fuseki:
    build: "./fuseki"
    ports:
      - 3030:3030
    environment:
      - ADMIN_PASSWORD=bd0
  bdoharmonization:
    build: "./bdoharmonization"
    ports:
      - 5000:5000
    links:
      - fuseki